//1. 顶部tab_1 常用
http://capi.douyucdn.cn/api/v1/getColumnDetail?client_sys=ios
{
    "error": 0,
    "data": [{
             "tag_id": "1",
             "short_name": "LOL",
             "tag_name": "\u82f1\u96c4\u8054\u76df",
             "pic_name": "c543faae97189c529c37b7741906d5a1.jpg",
             "icon_name": "613b6811048fc000ddb74af4320dfed9.jpg",
             "orderdisplay": "2",
             "rank_score": "0",
             "night_rank_score": "0",
             "nums": "20346",
             "push_ios": "1",
             "push_home": "1",
             "is_game_cate": "1",
             "cate_id": "1",
             "is_del": "0",
             "is_relate": "1",
             "push_vertical_screen": "0",
             "push_qqapp": "1",
             "broadcast_limit": "3",
             "pic_url": "http:\/\/staticlive.douyucdn.cn\/upload\/game_cate\/c543faae97189c529c37b7741906d5a1.jpg",
             "url": "\/directory\/game\/LOL",
             "icon_url": "http:\/\/staticlive.douyucdn.cn\/upload\/game_cate\/613b6811048fc000ddb74af4320dfed9.jpg",
             "count": 1591,
             "count_ios": 330
             }, {
             "tag_id": "2",
             "short_name": "How",
             "tag_name": "\u7089\u77f3\u4f20\u8bf4",
             "pic_name": "ff869b8da8231a3f2e8136f6d46e052b.jpg",
             "icon_name": "27cd6ec9c5d467ff37feda7f53687d7a.jpg",
             "orderdisplay": "5",
             "rank_score": "0",
             "night_rank_score": "0",
             "nums": "4030",
             "push_ios": "1",
             "push_home": "1",
             "is_game_cate": "1",
             "cate_id": "1",
             "is_del": "0",
             "is_relate": "1",
             "push_vertical_screen": "0",
             "push_qqapp": "1",
             "broadcast_limit": "3",
             "pic_url": "http:\/\/staticlive.douyucdn.cn\/upload\/game_cate\/ff869b8da8231a3f2e8136f6d46e052b.jpg",
             "url": "\/directory\/game\/How",
             "icon_url": "http:\/\/staticlive.douyucdn.cn\/upload\/game_cate\/27cd6ec9c5d467ff37feda7f53687d7a.jpg",
             "count": 176,
             "count_ios": 87
             }]
}

#顶部轮播图
http://capi.douyucdn.cn/api/v1/slide/6?version=2.291&client_sys=ios
{
    "error": 0,
    "data": [{
             "id": 318731,
             "title": "白开水的四国军棋拼杀！",
             "pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608291000045380.jpg",
             "tv_pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608291000047155.jpg",
             "room": {
             "room_id": "318731",
             "room_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/318731_160829101702.jpg",
             "vertical_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/318731_160829101702.jpg",
             "isVertical": 0,
             "cate_id": "113",
             "room_name": "【四国军棋】精益求精",
             "vod_quality": "0",
             "show_status": "1",
             "show_time": "1472432610",
             "owner_uid": "22028651",
             "specific_catalog": "",
             "specific_status": "0",
             "credit_illegal": "0",
             "is_white_list": "0",
             "cur_credit": "12",
             "low_credit": "4",
             "online": 5742,
             "nickname": "白开氺",
             "url": "\/318731",
             "game_url": "\/directory\/game\/qipai",
             "game_name": "棋牌娱乐",
             "game_icon_url": "https:\/\/staticlive.douyucdn.cn\/upload\/game_cate\/6ab23f74b5243fb851f0e213ba7c0caf.jpg",
             "show_details": "白开水，四国军旗知名棋手。直播时间早上9点至？？ 晚上7点至10半左右。 互粉群号：92292572 欢迎大家踊跃进群",
             "owner_avatar": "https:\/\/apic.douyucdn.cn\/upload\/avatar\/022\/02\/86\/51_avatar_big.jpg?rltime",
             "cdnsWithName": [{
                              "name": "主线路",
                              "cdn": "ws"
                              }, {
                              "name": "备用线路5",
                              "cdn": "tct"
                              }, {
                              "name": "备用线路2",
                              "cdn": "ws2"
                              }, {
                              "name": "备用线路3",
                              "cdn": "dl"
                              }],
             "is_pass_player": 0,
             "owner_weight": "14.49t",
             "fans": "16165",
             "column_id": "1"
             }
             }, {
             "id": 520346,
             "title": "史上最丰富的英语表情课！",
             "pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608290908047331.jpg",
             "tv_pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608290908049057.jpg",
             "room": {
             "room_id": "520346",
             "room_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/520346_160829102246.jpg",
             "vertical_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/520346_160829102246.jpg",
             "isVertical": 0,
             "cate_id": "195",
             "room_name": "斗鱼说—英语表演课，敢不敢喜欢姐姐",
             "vod_quality": "0",
             "show_status": "1",
             "show_time": "1472434470",
             "owner_uid": "8673047",
             "specific_catalog": "nana18",
             "specific_status": "1",
             "credit_illegal": "0",
             "is_white_list": "0",
             "cur_credit": "12",
             "low_credit": "4",
             "online": 17763,
             "nickname": "上虞娜娜",
             "url": "\/nana18",
             "game_url": "\/directory\/game\/yj",
             "game_name": "鱼教",
             "game_icon_url": "https:\/\/staticlive.douyucdn.cn\/upload\/game_cate\/42aaa89af76041b711a091374f6c8eb7.jpg",
             "show_details": "新浪微博：娜娜永远十八岁哇哈哈哈，群531025235。直播时间上午9：30-12：00，晚上8：00-9：30！（ps：两个飞机以上送房管，偶尔眼熟送，周榜第一微信） 上虞娜娜百货店https:\/\/shop159616687.taobao.com",
             "owner_avatar": "https:\/\/apic.douyucdn.cn\/upload\/avatar\/face\/201606\/14\/5e85daf4b062476d3d6118a5c4bf764b_big.jpg?rltime",
             "cdnsWithName": [{
                              "name": "主线路",
                              "cdn": "ws"
                              }, {
                              "name": "备用线路5",
                              "cdn": "tct"
                              }, {
                              "name": "备用线路2",
                              "cdn": "ws2"
                              }, {
                              "name": "备用线路3",
                              "cdn": "dl"
                              }],
             "is_pass_player": 0,
             "owner_weight": "11.51t",
             "fans": "195030",
             "column_id": "11"
             }
             }, {
             "id": 288016,
             "title": "英雄联盟五周年狂欢盛典重播",
             "pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608290836024925.jpg",
             "tv_pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608290836029757.jpg",
             "room": {
             "room_id": "288016",
             "room_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/288016_160829101951.jpg",
             "vertical_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/288016_160829101951.jpg",
             "isVertical": 0,
             "cate_id": "1",
             "room_name": "英雄联盟五周年狂欢盛典第二日重播",
             "vod_quality": "0",
             "show_status": "1",
             "show_time": "1472183672",
             "owner_uid": "19344409",
             "specific_catalog": "lol",
             "specific_status": "1",
             "credit_illegal": "0",
             "is_white_list": "0",
             "cur_credit": "12",
             "low_credit": "4",
             "online": 216470,
             "nickname": "Riot拳头",
             "url": "\/lol",
             "game_url": "\/directory\/game\/LOL",
             "game_name": "英雄联盟",
             "game_icon_url": "https:\/\/staticlive.douyucdn.cn\/upload\/game_cate\/613b6811048fc000ddb74af4320dfed9.jpg",
             "show_details": "英雄联盟2016赛季全球总决赛，斗鱼全程直播，更多精彩更多内容。9月29日—10月29日锁定斗鱼直播，给你一个不一样的总决赛体验！！我们不见不散！！！",
             "owner_avatar": "https:\/\/apic.douyucdn.cn\/upload\/avatar\/face\/201608\/25\/142c25ff26281729cd85ff5a710a943e_big.jpg?rltime",
             "cdnsWithName": [{
                              "name": "主线路",
                              "cdn": "ws"
                              }, {
                              "name": "备用线路5",
                              "cdn": "tct"
                              }, {
                              "name": "备用线路2",
                              "cdn": "ws2"
                              }, {
                              "name": "备用线路3",
                              "cdn": "dl"
                              }],
             "is_pass_player": 0,
             "owner_weight": "22.45t",
             "fans": "770608",
             "column_id": "1"
             }
             }, {
             "id": 6166,
             "title": "茂神虚空之遗第一视角",
             "pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608291010185389.jpg",
             "tv_pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608291010185811.jpg",
             "room": {
             "room_id": "6166",
             "room_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/6166_160829101656.jpg",
             "vertical_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/6166_160829101656.jpg",
             "isVertical": 0,
             "cate_id": "4",
             "room_name": "背背佳神族挺直身板战韩服矫正坐姿从我坐起",
             "vod_quality": "0",
             "show_status": "1",
             "show_time": "1472435220",
             "owner_uid": "209746",
             "specific_catalog": "cloudy",
             "specific_status": "1",
             "credit_illegal": "0",
             "is_white_list": "0",
             "cur_credit": "12",
             "low_credit": "4",
             "online": 3858,
             "nickname": "Cloudy",
             "url": "\/cloudy",
             "game_url": "\/directory\/game\/SC",
             "game_name": "星际争霸",
             "game_icon_url": "https:\/\/staticlive.douyucdn.cn\/upload\/game_cate\/6db9044e2f8a5f9b4e8b9e3e82302828.jpg",
             "show_details": "我的群号：20409809 优酷空间教学视频http:\/\/i.youku.com\/igcloudy",
             "owner_avatar": "https:\/\/apic.douyucdn.cn\/upload\/avatar\/000\/20\/97\/46_avatar_big.jpg?rltime",
             "cdnsWithName": [{
                              "name": "主线路",
                              "cdn": "ws"
                              }, {
                              "name": "备用线路5",
                              "cdn": "tct"
                              }, {
                              "name": "备用线路2",
                              "cdn": "ws2"
                              }, {
                              "name": "备用线路3",
                              "cdn": "dl"
                              }],
             "is_pass_player": 0,
             "owner_weight": "7.54t",
             "fans": "36423",
             "column_id": "1"
             }
             }, {
             "id": 107447,
             "title": "WE超 中单稳健操作",
             "pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608291006065287.jpg",
             "tv_pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608291006064202.jpg",
             "room": {
             "room_id": "107447",
             "room_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/107447_160829101659.jpg",
             "vertical_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/107447_160829101659.jpg",
             "isVertical": 0,
             "cate_id": "77",
             "room_name": "WE超--电竞慈父带子上分~",
             "vod_quality": "0",
             "show_status": "1",
             "show_time": "1472434145",
             "owner_uid": "4889635",
             "specific_catalog": "",
             "specific_status": "0",
             "credit_illegal": "0",
             "is_white_list": "0",
             "cur_credit": "12",
             "low_credit": "4",
             "online": 6739,
             "nickname": "zcoko1234",
             "url": "\/107447",
             "game_url": "\/directory\/game\/COS",
             "game_name": "英魂之刃",
             "game_icon_url": "https:\/\/staticlive.douyucdn.cn\/upload\/game_cate\/e6bc494d71712beaa3cf4df686bd20f4.jpg",
             "show_details": "天猫店https:\/\/weimeipu.tmall.hk(说我推荐的免费领20优惠券)                                                QQ群51320643        QQ373837250",
             "owner_avatar": "https:\/\/apic.douyucdn.cn\/upload\/avatar\/004\/88\/96\/35_avatar_big.jpg?rltime",
             "cdnsWithName": [{
                              "name": "主线路",
                              "cdn": "ws"
                              }, {
                              "name": "备用线路5",
                              "cdn": "tct"
                              }, {
                              "name": "备用线路2",
                              "cdn": "ws2"
                              }, {
                              "name": "备用线路3",
                              "cdn": "dl"
                              }],
             "is_pass_player": 0,
             "owner_weight": "1.63t",
             "fans": "24851",
             "column_id": "1"
             }
             }, {
             "id": 41829,
             "title": "kenny的皇室战争",
             "pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608291007137801.jpg",
             "tv_pic_url": "https:\/\/staticlive.douyucdn.cn\/upload\/signs\/201608291007131747.jpg",
             "room": {
             "room_id": "41829",
             "room_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/41829_160829101658.jpg",
             "vertical_src": "https:\/\/rpic.douyucdn.cn\/z1608\/29\/10\/41829_160829101658.jpg",
             "isVertical": 0,
             "cate_id": "190",
             "room_name": "【Kenny】新毒猪！平民玩家的福音",
             "vod_quality": "0",
             "show_status": "1",
             "show_time": "1472434699",
             "owner_uid": "962750",
             "specific_catalog": "kennycr",
             "specific_status": "1",
             "credit_illegal": "0",
             "is_white_list": "0",
             "cur_credit": "12",
             "low_credit": "4",
             "online": 3411,
             "nickname": "Kenny皇室战争",
             "url": "\/kennycr",
             "game_url": "\/directory\/game\/hszz",
             "game_name": "皇室战争",
             "game_icon_url": "https:\/\/staticlive.douyucdn.cn\/upload\/game_cate\/4ba688388a34ffbcc7c63b2c34c70b83.jpg",
             "show_details": "QQ交流群：122840288  \n新浪微博：Kenny皇室战争\n优酷空间：斗鱼Kenny皇室战争\n秋实手游:490元=14000钻 qs2016.taobao.com",
             "owner_avatar": "https:\/\/apic.douyucdn.cn\/upload\/avatar\/face\/201605\/08\/45ebb52949767c53a446a9967f8baacf_big.jpg?rltime",
             "cdnsWithName": [{
                              "name": "主线路",
                              "cdn": "ws"
                              }, {
                              "name": "备用线路5",
                              "cdn": "tct"
                              }, {
                              "name": "备用线路2",
                              "cdn": "ws2"
                              }, {
                              "name": "备用线路3",
                              "cdn": "dl"
                              }],
             "is_pass_player": 0,
             "owner_weight": "1.86t",
             "fans": "15412",
             "column_id": "9"
             }
             }]
}
            